import { Box, CssBaseline } from '@mui/material';
import * as React from 'react'
import Loader from 'src/ui-component/Loader';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { themeOptions } from 'src/theme/theme';

const theme = createTheme(themeOptions);

export const UseTerms = () =>{


    return (
        <React.Fragment>
             <ThemeProvider theme={theme}>
                <CssBaseline />
                <Box sx={{p:2}}>
                <h3>Responsable</h3>
<p>-Denominaci&oacute;n Social : Bienesdar.org&lt; br/&gt; -CIF / NIF : G99525594<br />-Nombre Comercial : Eduplat<br />&ndash; Responsable de Seguridad: <a href="https://www.google.com/url?q=https://www.linkedin.com/in/alvaroserra&amp;sa=D&amp;source=editors&amp;ust=1681918848834799&amp;usg=AOvVaw2zFU4nBgbYhG4qA-kgnY3N">Alvaro Serra</a></p>
<h3>Contacto</h3>
<p>&nbsp;-Email: [email protected]<br />-Formulario de contacto online:&nbsp;https://eduplat.org/contact/<br />-Perfiles en redes sociales: Facebook, Twitter, YouTube<a href="https://www.google.com/url?q=https://www.youtube.com/filmosofia&amp;sa=D&amp;source=editors&amp;ust=1681918848835351&amp;usg=AOvVaw3W8y8mAK3B5s5SMUHVIdwZ">,</a>&nbsp;LinkedIn<a href="https://www.google.com/url?q=https://es.linkedin.com/company/filmosofia&amp;sa=D&amp;source=editors&amp;ust=1681918848835537&amp;usg=AOvVaw2_xl2xj4okdKgJ-SDGGSaJ">,</a>&nbsp;Instagram</p>
<h3>Registros:</h3>
<p>-Registro: registro nacional de asociaciones (Ministerio del Interior) el 25/04/2018 en el GRUPO 1, SECCI&Oacute;N 1, N&ordm; 615536.</p>
<p>- Registro EU: Registrada en la<a href="https://www.google.com/url?q=https://webgate.ec.europa.eu/&amp;sa=D&amp;source=editors&amp;ust=1681918848836133&amp;usg=AOvVaw1l6BuXMQXrL962TwuzXsBd">Comisi&oacute;n Europea</a>&nbsp;desde el 29-12-2020 con el n&uacute;mero E1026498<br />&ndash;Registro de Tratamientos conforme al RGPD:&nbsp;Clientes/Proveedores, Listas de Correo, Empleados, Selecci&oacute;n de Personal, Videovigilancia, Formaci&oacute;n y Usuarios Web.<br />-Nombre de dominio (sitio web):&nbsp;https://Eduplat.com</p>
<p>LEA CON DETENIMIENTO NUESTRAS CONDICIONES DE USO<br />&nbsp;CONSTITUYEN UN ACUERDO LEGAL ENTRE EL USUARIO Y EDUPLAT</p>
<p>CONSULTE TAMBI&Eacute;N LA POL&Iacute;TICA DE PRIVACIDAD</p>
<p>El sitio Web http://eduplat.org, y cualquiera de los subdominios de este (cualquiera de ellos referido como &ldquo;Sitio&rdquo;) es propiedad de Bienesdar. (&ldquo;Eduplat&rdquo;), que se encarga de su funcionamiento; estas Condiciones de uso (&ldquo;CDU&rdquo;) rigen la utilizaci&oacute;n que realice del Contenido (definido a continuaci&oacute;n). Siempre que use o intente usar el Sitio (ahora o en cualquier momento posterior a alguna enmienda o modificaci&oacute;n del Sitio o de estas CDU) acepta quedar vinculado por estas CDU y cumplir estas CDU, las cuales constituyen un acuerdo legal entre el usuario y Eduplat. Nuestra pol&iacute;tica de privacidad forma parte de estas CDU y se adjunta como referencia. Conviene que la revise tambi&eacute;n con detenimiento ya que forma parte de su acuerdo con Eduplat. Las referencias que se hagan a usted como usuario implican registros individuales o usos de su Cuenta (definida a continuaci&oacute;n). El uso de la palabra &ldquo;incluido&rdquo; y derivados implica que se est&aacute;n dando ejemplos que, en ning&uacute;n caso, limitan ni excluyen otros supuestos.</p>
<p>Eduplat se reserva el derecho de enmendar y modificar estas CDU y de alterar o cambiar en todo o en parte el Sitio en cualquier momento y ocasionalmente, cambios que ser&aacute;n efectivos, en cada caso, cuando se publiquen o se muestran en el Sitio. Se recomienda que revise estas CDU con frecuencia para estar al tanto de las CDU que se aplican en su caso..</p>
<p>Se le otorga un derecho y una licencia intransferibles, limitados y no exclusivos de acceder, usar y mostrar privadamente el Sitio exclusivamente para su uso personal, siempre sujeto al cumplimiento de estas CDU. Esta licencia no incluye ninguna reventa ni uso comercial de este Sitio o de sus contenidos; ninguna recopilaci&oacute;n o uso de listados de productos, descripciones o precios; ning&uacute;n uso derivado de este Sitio; ninguna descarga o copia de informaci&oacute;n de cuentas para beneficio de otro comerciante; ni ning&uacute;n uso de herramientas ni de robots de extracci&oacute;n y recopilaci&oacute;n de datos. No puede enmarcar en otras p&aacute;ginas ni utilizar t&eacute;cnicas para ello con vistas a usar, rodear o encerrar el nombre, marcas comerciales, marcas de servicio, logotipo u otra informaci&oacute;n de propiedad (incluidas im&aacute;genes, texto, dise&ntilde;o de p&aacute;gina o formato) de Eduplat o de nuestras filiales y subsidiarias sin el consentimiento expreso y por escrito de Eduplat. No puede utilizar metaetiquetas ni ning&uacute;n otro &ldquo;texto oculto&rdquo; con el nombre o las marcas comerciales de Eduplat sin su consentimiento expreso y por escrito.</p>
<p>Como condici&oacute;n para usar este Sitio, manifiesta y garantiza que no usar&aacute; el Sitio para fines il&iacute;citos o prohibidos por estas CDU. Si vulnera cualquiera de estas CDU, se cancelar&aacute; autom&aacute;ticamente la autorizaci&oacute;n con la que cuenta para usar este Sitio y podr&iacute;a ser objeto de sanciones civiles y penales.</p>
<p>Contenido y Software.&nbsp;Tanto el Sitio como todo lo que se muestra o se pone a su disposici&oacute;n en relaci&oacute;n con el Sitio es propiedad de Eduplat, sus subsidiarias, filiales, distribuidores, titulares y otorgantes de las licencias y de los derechos de contenido, y se reservan todos los derechos no otorgados expresa y espec&iacute;ficamente al usuario por la presente. Utilizaremos el t&eacute;rmino &ldquo;Contenido&rdquo; para hacer referencia a todo texto, informaci&oacute;n, audio o elementos visuales presentes en este Sitio y legibles mec&aacute;nicamente o por personas, incluido todo el texto, gr&aacute;ficos, im&aacute;genes, ilustraciones, fotograf&iacute;as, animaciones, v&iacute;deo, audio o trabajos audiovisuales, tr&aacute;iler cinematogr&aacute;ficos, obras por episodios, v&iacute;deos, pel&iacute;culas y fotograf&iacute;a digital, dise&ntilde;os, logotipos, informaci&oacute;n y &ldquo;Software&rdquo;; por Software se entiende software, programaci&oacute;n inform&aacute;tica, c&oacute;digo, archivos, im&aacute;genes y texto incorporado en el software o generado por &eacute;l, toda la documentaci&oacute;n, informaci&oacute;n y datos que acompa&ntilde;an al Software, incluidos todo el c&oacute;digo fuente y objeto, scripts, utilidades, conjuntos de sentencias, instrucciones y bases de datos asociadas con &eacute;l. El t&eacute;rmino &ldquo;Contenido&rdquo; incluye tambi&eacute;n todos los derechos de propiedad intelectual y de &iacute;ndole similar aplicables al Contenido.</p>
<p>S&oacute;lo podr&aacute; usar el contenido seg&uacute;n las directrices incluidas en estas CDU, en cualquier licencia de usuario final aplicable al Software o de cualquier otro modo al que hayamos accedido por escrito. El Contenido est&aacute; protegido por leyes, normativas y tratados en Espa&ntilde;a e internacionalmente y, a menos que Eduplat lo permita de forma expresa por escrito, no podr&aacute; copiar, publicar, distribuir, usar, capturar, reproducir, realizar, transferir, vender, modificar, ni crear trabajos derivados, volver a publicar, cargar, adaptar, portar, traducir, editar, transmitir, mostrar p&uacute;blicamente, incluir en marcos, vincular o usar de cualquier otro modo el Contenido; tampoco podr&aacute; otorgar licencias o sublicencias respecto a &eacute;l. Si infringe estas CDU, puede incurrir en responsabilidad civil y ser objeto de sanciones civiles y penales.</p>
<p>Si obtiene Software de Eduplat (a trav&eacute;s de este Sitio, en un establecimiento de venta minorista o de cualquier otro modo),Eduplat le otorga una licencia con arreglo a las condiciones del contrato de licencia del usuario final pertinentes al Software; deber&aacute; consultar el contrato de licencia del usuario final concreto para conocer los t&eacute;rminos y las condiciones de la licencia que ha recibido para el uso de un producto de Software en particular. Si hay disponible software de terceros (&ldquo;Software de terceros&rdquo;) a trav&eacute;s del Sitio, sus derechos para obtener y usar dicho Software de terceros estar&aacute;n sujetos al contrato de licencia y cualquier otra condici&oacute;n que proporcione dicho tercero en relaci&oacute;n con tal Software. Respecto a todo el Software de Eduplat que obtenga, se le otorga derecho y licencia para lo siguiente: (1) usar el Software en un &uacute;nico equipo simult&aacute;neamente y s&oacute;lo seg&uacute;n las instrucciones y el contrato de licencia proporcionado con el Software; y (2) realizar copia de seguridad, pero no copias de otro tipo. En ning&uacute;n momento se le permite: (1) otorgar sublicencias, proporcionar, prestar, arrendar o poner el Software a disposici&oacute;n de terceros de cualquier otra forma; (2) usar el Software comercialmente; (3) crear trabajos derivados, modificar, adaptar o traducir ning&uacute;n Software; (4) realizar ingenier&iacute;a inversa, descompilar o desensamblar el Software, ni intentar de alg&uacute;n otro modo obtener su c&oacute;digo fuente; (5) eliminar o alterar ning&uacute;n aviso de copyright, marca comercial o propiedad; ni (5) usar el Software de ninguna forma que no est&eacute; establecida en estas CDU, el contrato de licencia aplicable o en cualquier otro escrito realizado expresamente por Eduplat.</p>
<p>Sin limitaci&oacute;n, todas las marcas comerciales, marcas de servicio, nombres, marcas, logotipos e identificaci&oacute;n distintiva, incluidas Eduplat, La Cinetera, Talentorama, Aula Eduplat, son propiedad de Eduplat, sus filiales o sus distribuidores, otorgantes de licencia, propietarios de contenido o anunciantes, y no tiene ning&uacute;n derecho en absoluto a utilizarlas para ning&uacute;n fin.</p>
<p>Productos y compras. Aunque Eduplat trata de que las descripciones de los productos en su Sitio se ajusten a la realidad tanto como sea posible, Eduplat no garantiza que las descripciones de los productos o el Contenido sean precisos, completos o fiables ni que est&eacute;n actualizados ni libres de errores. La &uacute;nica reparaci&oacute;n posible, en caso de que alg&uacute;n producto de Eduplat (incluido Software) no funcione correctamente o no se ajuste a las especificaciones y descripciones que de &eacute;l se dieron, incluso en el supuesto de que alguna acci&oacute;n no sirva a su fin esencial, es devolver el producto sin usar y obtener el reembolso completo del precio de la compra.</p>
<p>Pol&iacute;tica de privacidad. <a href="https://www.google.com/url?q=https://whitehat-school.com/privacy-policy&amp;sa=D&amp;source=editors&amp;ust=1681918848838012&amp;usg=AOvVaw0YpZSSUVn3CBRgyc1JbUz1">NUEVA ADAPTACI&Oacute;N A LA GDPR</a></p>
<p>Env&iacute;os no solicitados. No nos env&iacute;e ninguna idea creativa original, sugerencia, contenido ni material con la intenci&oacute;n de que lo miremos o evaluemos para nuestro uso ni el de terceros. Declinamos cualquier obligaci&oacute;n o responsabilidad respecto a env&iacute;os no solicitados y si nos env&iacute;a alguno para cualquiera de los fines mencionados, pasar&aacute; a ser autom&aacute;ticamente de nuestra propiedad, sin obligaci&oacute;n de confidencialidad ni restricciones de uso o revelaci&oacute;n. Pasaremos a ser titulares en exclusiva de todos los derechos sobre env&iacute;os no solicitados, incluidos trabajos derivados, en todo el mundo, y tendremos derecho al uso sin restricciones para cualquier prop&oacute;sito, sin vernos obligados a atribuir, compensar ni nada de &iacute;ndole similar a la persona que env&iacute;o el material ni a ninguna otra.</p>
<p>Renuncia de garant&iacute;as. EDUPLAT NO GARANTIZA QUE EL USO DEL SITIO PUEDA REALIZARSE SIN INTERRUPCIONES NI ERRORES, NI QUE EL SITIO FUNCIONAR&Aacute; DE UN MODO EN PARTICULAR, NI QUE EL SITIO O EL CONTENIDO (INCLUIDO EL SOFTWARE QUE DESCARGUE) EST&Eacute; LIBRE DE VIRUS, GUSANOS, TROYANOS U OTRO C&Oacute;DIGO O MATERIAL MALICIOSO, DA&Ntilde;INO O DESTRUCTIVO. EL SITIO Y TODO EL CONTENIDO EST&Aacute;N DISPONIBLES &ldquo;TAL CUAL&rdquo;, CON TODOS SU FALLOS; EDUPLAT NO OFRECE GARANT&Iacute;A DE NING&Uacute;N TIPO Y RENUNCIA CONCRETAMENTE A TALES GARANT&Iacute;AS, YA SEAN EXPRESAS O IMPL&Iacute;CITAS, INCLUIDAS, PERO SIN LIMITARSE A ELLAS, LAS GARANT&Iacute;AS IMPL&Iacute;CITAS DE COMERCIABILIDAD, ADECUACI&Oacute;N PARA UN FIN O CARGO PARTICULAR Y NO INFRACCI&Oacute;N DE DERECHOS DE PROPIEDAD.</p>
<p>NO SE RECOMIENDA QUE PASE A DEPENDER DE NING&Uacute;N CONTENIDO DEL SITIO, NI DE LAS COMUNICACIONES CON EL SITIO, YA SEAN ENTRANTES O SALIENTES, Y Eduplat NO GARANTIZA QUE EL CONTENIDO, LAS FUNCIONES O CARACTER&Iacute;STICAS SEAN PRECISAS, COMPLETAS U OPORTUNAS. ES RESPONSABILIDAD SUYA REALIZAR COPIAS DE SEGURIDAD Y VELAR POR LA SEGURIDAD DE SUS SISTEMAS; Eduplat NO SER&Aacute; RESPONSABLE DE NING&Uacute;N COSTE O DA&Ntilde;O QUE PUEDA SURGIR DIRECTA O INDIRECTAMENTE DEL USO QUE REALICE DEL SITIO O DEL CONTENIDO.</p>
<p>BIENESDAR, SU MATRIZ EDUPLAT, SUBSIDIARIAS, FILIALES, DISTRIBUTORES Y OTORGANTES DE LICENCIA RENUNCIAN A TODA RESPONSABILIDAD ANTE CUALQUIER DA&Ntilde;O DIRECTO, INDIRECTO, FORTUITO, DERIVADO, ESPECIAL, EJEMPLAR, PUNITIVO O DE CUALQUIER OTRA &Iacute;NDOLE QUE PUEDA SURGIR O ESTAR RELACIONADO DE CUALQUIER MODO CON EL SITIO, CONTENIDO, SOFTWARE, CUALQUIER PRODUCTO O SERVICIO U OTRO MATERIAL O INFORMACI&Oacute;N. CON INDEPENDENCIA DE LA FORMA DE LA ACCI&Oacute;N O DE LA BASE DE LA RECLAMACI&Oacute;N E INCLUSO SI SE LE HA NOTIFICADO DE LA POSIBILIDAD DE DICHOS DA&Ntilde;OS.</p>
<p>COMO &Uacute;NICA REPARACI&Oacute;N EN CASO DE INSATISFACCI&Oacute;N, PUEDE DEJAR DE USAR EL SITIO, EL CONTENIDO, LOS PRODUCTOS Y SERVICIOS IMPLICADOS.<br />ALGUNAS JURISDICCIONES NO PERMITEN LIMITACIONES DE GARANT&Iacute;AS IMPL&Iacute;CITAS, POR LO QUE ALGUNAS DE LAS RENUNCIAS, EXCLUSIONES O LIMITACIONES PUEDEN NO APLICARSE A SU PERSONA; SI ES EL CASO CONTAR&Aacute; CON M&Aacute;S DERECHOS.</p>
<p>Rescisi&oacute;n. Eduplat se reserva el derecho a cancelar el acceso a este Sitio y a cualquier contenido, en todo o en parte, con o sin motivo para ello y con o sin que medie aviso previo en cualquier momento. No podr&aacute; iniciar ninguna acci&oacute;n contra Eduplat transcurrido un a&ntilde;o de la fecha en que apareci&oacute; por primera vez la causa de acci&oacute;n.</p>
<p>Aviso de copyright<br />&nbsp;Si considera que cualquier contenido infringe sus derechos de copyright o los de otra persona, siga los procedimientos e instrucciones que indicamos en nuestra secci&oacute;n de avisos y procedimientos para interponer reclamaciones por infracci&oacute;n de copyright con objeto de notificarlo a nuestro agente de copyright.</p>
<p>Acuerdo total. Estas CDU, incluida la pol&iacute;tica de privacidad, constituyen el acuerdo total entre el usuario y Eduplat en relaci&oacute;n con el contenido, con prioridad sobre cualquier interpretaci&oacute;n anterior, contradictoria o de otra &iacute;ndole en relaci&oacute;n con el contenido. Nadie excepto Eduplat, y del modo descrito espec&iacute;ficamente en este documento, puede realizar enmiendas o modificaciones a las CDU, ya sea por l&iacute;nea de comportamiento o de cualquier otro modo.</p>
<h2>Condiciones de Uso</h2>
<p>Este Sitio Web contiene textos elaborados con fines meramente informativos o divulgativos, que pueden no reflejar el estado actual de la legislaci&oacute;n o la jurisprudencia, y que se refieren a situaciones generales, por lo que su contenido no debe ser aplicado necesariamente por el usuario a casos concretos.</p>
<p>En esta web se detallan los servicios ofrecidos por &ldquo;Eduplat&rdquo;. Su uso implica la aceptaci&oacute;n de las siguientes condiciones, declinando realizar cualquier reclamaci&oacute;n sobre las mismas:</p>
<ol start="1">
<li>a) El uso de esta web est&aacute; dirigido a personas mayores de edad.</li>
<li>b) &ldquo;Eduplat&rdquo; podr&aacute; modificar el contenido de la web, sus servicios, tarifas, garant&iacute;as, etc., en cualquier momento y sin previo aviso.</li>
<li>c) &ldquo;Eduplat&rdquo; puede poner a disposici&oacute;n del usuario enlaces u otros elementos que permiten el acceso hacia otros sitios web pertenecientes a terceros. No comercializamos los productos y servicios de dichas p&aacute;ginas enlazadas, ni asumimos ning&uacute;n tipo de responsabilidad sobre las mismas, ni sobre la informaci&oacute;n contenida en ellas, ni su veracidad o licitud, ni de cualesquiera efectos que pudieran derivarse. En todo caso, &ldquo;Eduplat&rdquo; manifiesta que proceder&aacute; a la retirada inmediata de cualquier contenido que pudiera contravenir la legislaci&oacute;n nacional o internacional, la moral o el orden p&uacute;blico, procediendo a la retirada inmediata de la redirecci&oacute;n a dicho sitio web, poniendo en conocimiento de las autoridades competentes el contenido en cuesti&oacute;n.</li>
<li>d) Los precios indicados en la web, de haberlos, ser&aacute;n v&aacute;lidos salvo error tipogr&aacute;fico, y susceptibles de cambios sin previo aviso.</li>
<li>e) No es necesario registrarse en la web, ni facilitar ning&uacute;n tipo de dato personal, para navegar por la misma.</li>
<li>f) &ldquo;Eduplat&rdquo; no puede garantizar el funcionamiento ininterrumpido o totalmente libre de errores de esta web. Por tanto, no nos hacemos responsables de ning&uacute;n da&ntilde;o causado por el uso de este sitio.</li>
<li>g) &ldquo;Eduplat&rdquo; ofrece sus servicios y productos de manera indefinida, pudiendo, no obstante, suspender la prestaci&oacute;n de los mismos, unilateralmente y sin previo aviso.</li>
<li>h) &ldquo;Eduplat&rdquo; no se har&aacute; responsable de los da&ntilde;os y perjuicios, propios o a terceros, producidos por un mal uso de esta web por parte del cliente.</li>
<li>i) El usuario se compromete a no utilizar esta web ni los servicios ofrecidos en ella para la realizaci&oacute;n de actividades contrarias a la ley, al orden p&uacute;blico o a estas condiciones.</li>
<li>j) &ldquo;Eduplat&rdquo; no se responsabiliza de los virus que tengan su origen en una transmisi&oacute;n telem&aacute;tica infiltrados por terceros generados con la finalidad de obtener resultados negativos para un sistema inform&aacute;tico.</li>
<li>k) &ldquo;Eduplat&rdquo; no se hace responsable de la informaci&oacute;n y contenidos almacenados, a t&iacute;tulo enunciativo pero no limitativo, en foros, chat&acute;s, generadores de blogs, comentarios, redes sociales o cualesquiera otro medio que permita a terceros publicar contenidos de forma independiente en la p&aacute;gina web del prestador. No obstante y en cumplimiento de lo dispuesto en el art. 11 y 16 de la LSSI-CE, &ldquo;Eduplat&rdquo; se pone a disposici&oacute;n de todos los usuarios, autoridades y fuerzas de seguridad, y colaborando de forma activa en la retirada o en su caso bloqueo de todos aquellos contenidos que pudieran afectar o contravenir la legislaci&oacute;n nacional, o internacional, derechos de terceros o la moral y el orden p&uacute;blico. En caso de que el usuario considere que existe en el sitio web alg&uacute;n contenido que pudiera ser susceptible de esta clasificaci&oacute;n, se ruega lo notifique de forma inmediata al administrador del sitio web.</li>
<li>l) Este sitio web ha sido revisado y probado para que funcione correctamente. En principio, puede garantizarse el correcto funcionamiento los 365 d&iacute;as del a&ntilde;o, 24 horas al d&iacute;a. No obstante, &ldquo;Eduplat&rdquo; no descarta la posibilidad de que existan ciertos errores de programaci&oacute;n, o que acontezcan causas de fuerza mayor, cat&aacute;strofes naturales, huelgas, o circunstancias semejantes que hagan imposible el acceso a la p&aacute;gina web.</li>
<li>m) Las opiniones vertidas en los mismos no reflejan necesariamente los puntos de vista de &ldquo;Eduplat&rdquo;. El contenido de los art&iacute;culos publicados en este Sitio Web no puede ser considerado, en ning&uacute;n caso, sustitutivo de asesoramiento legal. El usuario no debe actuar sobre la base de la informaci&oacute;n contenida en este Sitio Web sin recurrir previamente al correspondiente asesoramiento profesional.</li>
</ol>
<p>En definitiva, el usuario es el &uacute;nico responsable del uso que realice de los servicios, contenidos y enlaces incluidos esta web. Estas CDU se modificaron por &uacute;ltima vez e 27 de Diciembre de 2018 y tienen efecto inmediato</p>

                </Box> 
            </ThemeProvider>
        </React.Fragment>
    )
}